### ISSUE TITLE
Reading-Order

### ISSUE THREAD

**Issue by deepseek** [nrhine1/deep_imitative_models#4]
@nrhine1 Hi there,

Can inverse reinforcement learning be used to predict the `Reading-Order` of text documents
1. My Groundtruth is image documents and their xml labels, having organized text regions,
example (1st paragraph, 2nd paragraph, 3rd paragraph, etc..)
2. I want to train a model to learn the concept of human reading order.
3. Finally, I will use the trained model on image documents with text regions, example ( paragraph, paragraph, paragraph), and the model would tell which paragraph is 1st, which is 2nd, etc...

- Which algorithm you recommend to use
- do you have any suggestions about anything
- will it generalize to other documents

![readingorder](https://user-images.githubusercontent.com/49877135/82798813-bf8ed480-9e81-11ea-9983-ec5d4d0d731f.jpg)

**Comment by nrhine1** [comment]
Hi @deepseek -- that sounds like an interesting problem. However, a github issue on this repository is not the proper place to discuss it, as github issues are meant to address issues with the project's code. Document reading order prediction is not in the scope of this project, although you could try an imitation learning approach like DIM for it. Hope that helps!
